name: Consultant App CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  vuejs-site-build-and-upload:
    runs-on: ubuntu-latest

    steps:

      # Step 1: Checkout Repository
      - name: Checkout Source Code
        uses: actions/checkout@v4

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      # Step 3: Install Dependencies
      - name: Install Dependencies
        run: npm install

      # Step 4: Build Vue JS Application
      - name: Build Application
        run: npm run build

      # Step 5: Upload Build Artifact
      - name: Upload Dist Folder
        uses: actions/upload-artifact@v4
        with:
          name: vue-build-files
          path: dist